language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-19mode
  - rbx-2
gemfile:
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4_1.gemfile
  - gemfiles/activesupport_4_2.gemfile
  - gemfiles/activesupport_5_0.gemfile
  - gemfiles/activesupport_5_1.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/activesupport_5_0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/activesupport_5_1.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/activesupport_5_0.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/activesupport_5_1.gemfile
